model:
  base_learning_rate: 4.5e-06
  target: twofive.models.dd.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    image_key: depth
    ddconfig:
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: twofive.modules.autoencoder.loss.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 1
        disc_start: 50001
        disc_weight: 0.75
        codebook_weight: 1.0
data:
  target: cutlit.DataModuleFromConfig
  params:
    batch_size: 3
    wrap: false
    train:
      target: twofive.data.imagenet.ImageNetTrainWithDepth
      params:
        size: 256
    validation:
      target: twofive.data.imagenet.ImageNetValidationWithDepth
      params:
        size: 256
